# Introdução


Os modelos gráficos probabilísticos são representações gráficas da dependência condicional entre variáveis aleatórias.  Essa relação probabilística é expressa por meio de grafos. Tais modelos têm sido alguns dos principais interesses da área de aprendizado de máquina nas últimas duas décadas [@ghahramani2015probabilistic]. Dentre esses modelos, as redes bayesianas - também conhecidas como redes de crença, redes casuais e gráficos de dependência probabilística - são representadas por um tipo específico de grafo denominado grafo acíclico direcionado. Assim, são modelos gráficos que representam, de forma visual, as dependências probabilísticas entre um conjunto de variáveis aleatórias  [@nagarajan2013bayesian]. Elas podem ser utilizadas para tarefas de raciocínio diagnóstico, preditivo e, até mesmo, causal [@korb2010bayesian]. Além de serem amplamente exploradas na area de modelagem estatística, são também utilizadas em outros enredos, um destes enredos pode ser visto como uma subárea da Inteligência Artificial, denominada Inteligência Artificial Probabilística [@ghahramani2015probabilistic].

As redes bayesianas surgiram no final da década de 80, desenvolvidas por Judea Pearl [@pearl1988probb], filósofo e cientista da computação, com o intuito de facilitar as tarefas de predição, indução e dedução em sistemas de inteligência artificial [@pearl2000introduction]. Os trabalhos de Judea Pearl têm sido referência em estudos probabilísticos nas áreas de análise contrafactual, equações estruturais, causalidade e inteligência artificial.


